### ISSUE TITLE
cds add mta shows warning and missing module

### ISSUE THREAD

**Issue by lvhengel** [SAP-samples/cloud-cap-risk-management#9]
Hi,

I am running through the tutorial "Deploy Your Multi-Target Application (MTA)"
with the latest @sap/cds-dk version 4.5.2

In Step 5: Generate MTA deployment descriptor (mta.yaml) I get the following warning after I run `cds add mta`

_[init] - No SAP HANA service binding defined in the requires section of the project's package.json. Database module omitted_

In the generated mta file I am then missing the following module
 
```
 # -------------------- SIDECAR MODULE ------------------------
 - name: cpapp-db-deployer
 # ------------------------------------------------------------
   type: hdb
   path: gen/db
   parameters:
     buildpack: nodejs_buildpack
   requires:
    # 'hana' and 'xsuaa' resources extracted from CAP configuration
    - name: cpapp-db
    - name: cpapp-uaa
```

When I run the `cds add mta` with the older version @sap/cds-dk@4.4.2 it works fine. No warning and the module is there.

Kind regards,
Leo
